<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>files</key>
	<dict>
		<key>Resources/Base.lproj/MainMenu.nib</key>
		<data>
		ri4V76O1rVG/NrWD8uztvWb1ego=
		</data>
		<key>Resources/clicking.icns</key>
		<data>
		l0E/H8HzS3JwAEtgsVV5PhbOh88=
		</data>
		<key>Resources/clicking1.icns</key>
		<data>
		u6KI6yo6K2Kqr6vI3RsOng2NDSM=
		</data>
		<key>Resources/clicking2.icns</key>
		<data>
		6Ze8+heef+tNDM2eqbgFi2n/h4w=
		</data>
		<key>Resources/clicking3.icns</key>
		<data>
		zzdwRkL+6fjtfgN7BOYzsfW4q4Y=
		</data>
		<key>Resources/default.icns</key>
		<data>
		xGpugHIc1fNUMO0YVJM29EhKLyY=
		</data>
		<key>Resources/paused.icns</key>
		<data>
		Fic68zv/N7jBOqWzPaqPaR876KE=
		</data>
		<key>Resources/waiting.icns</key>
		<data>
		HtpAcNuO8Z8XMnpKhf+bMGQBNL0=
		</data>
	</dict>
	<key>files2</key>
	<dict>
		<key>Frameworks/ShortcutRecorder.framework</key>
		<dict>
			<key>cdhash</key>
			<data>
			Q5Ft17r59crXBHvXa7e+a8WYggs=
			</data>
			<key>requirement</key>
			<string>identifier "com.kulakov.ShortcutRecorder" and anchor apple generic and certificate leaf[subject.CN] = "Apple Development: tianji010@qq.com (HCSTN596J7)" and certificate 1[field.1.2.840.113635.100.6.2.1] /* exists */</string>
		</dict>
		<key>Resources/Base.lproj/MainMenu.nib</key>
		<dict>
			<key>hash2</key>
			<data>
			8iYHRBn8OY1djRuFoCNTzVxfeKuWCdtXLdtL1IFLnNI=
			</data>
		</dict>
		<key>Resources/clicking.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			ZyVY80o8Xu7gOXMVzBsYztmvweUO60Rsd2hfLyjQQ2A=
			</data>
		</dict>
		<key>Resources/clicking1.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			0t5F/s3v3mKQJvVX2VsUFxUFMJ00sGq61SP7+IeQex8=
			</data>
		</dict>
		<key>Resources/clicking2.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			QjnvfdVcIo3oajr/hZSZxbVLKltciVdZlCoP1Cr7e8I=
			</data>
		</dict>
		<key>Resources/clicking3.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			t8r2lcP+JXdW3NQmosjApwCL64BwU+yM9T8Ms3xDD0U=
			</data>
		</dict>
		<key>Resources/default.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			5dsh9SbfHCihrwnAcw2GFJB3FnSs3BJvmMm6Mwa9kzY=
			</data>
		</dict>
		<key>Resources/paused.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			etM7HuoOUlwKvFOjETdqeKF5V67YG0yi1z2ZTcOyXDI=
			</data>
		</dict>
		<key>Resources/waiting.icns</key>
		<dict>
			<key>hash2</key>
			<data>
			fa04eLr/0wyy1cF9iaNX9I7wmEcwBrL0DpuLxhz7hF0=
			</data>
		</dict>
	</dict>
	<key>rules</key>
	<dict>
		<key>^Resources/</key>
		<true/>
		<key>^Resources/.*\.lproj/</key>
		<dict>
			<key>optional</key>
			<true/>
			<key>weight</key>
			<real>1000</real>
		</dict>
		<key>^Resources/.*\.lproj/locversion.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>1100</real>
		</dict>
		<key>^Resources/Base\.lproj/</key>
		<dict>
			<key>weight</key>
			<real>1010</real>
		</dict>
		<key>^version.plist$</key>
		<true/>
	</dict>
	<key>rules2</key>
	<dict>
		<key>.*\.dSYM($|/)</key>
		<dict>
			<key>weight</key>
			<real>11</real>
		</dict>
		<key>^(.*/)?\.DS_Store$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>2000</real>
		</dict>
		<key>^(Frameworks|SharedFrameworks|PlugIns|Plug-ins|XPCServices|Helpers|MacOS|Library/(Automator|Spotlight|LoginItems))/</key>
		<dict>
			<key>nested</key>
			<true/>
			<key>weight</key>
			<real>10</real>
		</dict>
		<key>^.*</key>
		<true/>
		<key>^Info\.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^PkgInfo$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^Resources/</key>
		<dict>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^Resources/.*\.lproj/</key>
		<dict>
			<key>optional</key>
			<true/>
			<key>weight</key>
			<real>1000</real>
		</dict>
		<key>^Resources/.*\.lproj/locversion.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>1100</real>
		</dict>
		<key>^Resources/Base\.lproj/</key>
		<dict>
			<key>weight</key>
			<real>1010</real>
		</dict>
		<key>^[^/]+$</key>
		<dict>
			<key>nested</key>
			<true/>
			<key>weight</key>
			<real>10</real>
		</dict>
		<key>^embedded\.provisionprofile$</key>
		<dict>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^version\.plist$</key>
		<dict>
			<key>weight</key>
			<real>20</real>
		</dict>
	</dict>
</dict>
</plist>
